-- CreateEnum
CREATE TYPE "Topic" AS ENUM ('GLOBAL', 'SPORTS', 'POLITICS', 'TECHNOLOGY', 'ENTERTAINMENT', 'BUSINESS', 'HEALTH', 'SCIENCE', 'EDUCATION', 'TRAVEL', 'FOOD', 'FASHION', 'LIFESTYLE', 'RELATIONSHIPS');

-- AlterTable
ALTER TABLE "Question" ADD COLUMN     "topic" "Topic" NOT NULL DEFAULT 'GLOBAL';
