version: "3.8"

services:
  db:
    container_name: db
    image: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    env_file:
      - "./backend/.env"
    volumes:
      - "db-data:/var/lib/postgresql/data"

  redis:
    container_name: redis
    image: redis
    restart: on-failure
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - "redis-data:/data"
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: minio-storage
    ports:
      - "9001:9001"
      - "9000:9000" # for the minio api
    env_file:
      - "./backend/.env"
    command: 'server /data --console-address ":9001"'
    restart: on-failure
    volumes:
      - "minio-data:/data"

volumes:
  minio-data:
  db-data:
  redis-data: